sudo: required
language: c
script:
# The build.sh need LZ4 and ubuntu 12.xx not support 'LZ4' officialy
- sudo add-apt-repository ppa:nathan-renniewaldock/ppa -y
- sudo apt-get update
#
# Travis CI Script by Caio Oliveira aka Caio99BR <caiooliveirafarias0@gmail.com>
#
# Toolchain Choice
# This will clone TeamVee Prebuilt Toolchains in directory described in build.sh
#
# Branchs available is:
# Linaro Branch is "master" | (1) 4.6.2 / (2) 4.7.3

# Toolchain select here is Linaro 4.7.3
- export ntoolchainbranch="master"
- export ntoolchainchoice="2"
- git clone -b "${ntoolchainbranch}" "https://github.com/JonasCardoso/Toolchain "../Toolchain"

# This will call build.sh with following parameters inside ${nbasebuildsh}:
#
# 'export ndevicechoice="#"'
# 'export nbasebuildsh="${ndevice}${ndevicechoice}${ntoolchain}${nbuild}q""'
# 'source build.sh <<< "${nbasebuildsh}"'
# 'export zipfile#="${zipfile}"'
#
# ${ndevice} = "2" is "Clean Kernel" and "3" is "Device Choice"
- ndevice="23"
# ${ndevicechoice} is "Number of Choice under Device Choice"
# ${ntoolchain} = "4" is "Toolchain Choice", ${ntoolchainchoice} is your Toolchain Choice
# and "o" is to disable/enable output when building kernel
- ntoolchain="4${ntoolchainchoice}o"
# ${nbuild} = "5" is "Build Kernel" and "6" is "Zip the kernel and Modules"
- nbuild="56"
# Last "q" is to Exit of Script

# For LG L5 NFC | E610
- export ndevicechoice="0"
- export nbasebuildsh="${ndevice}${ndevicechoice}${ntoolchain}${nbuild}q"
- source build.sh <<< "${nbasebuildsh}"
- export zipfile0="${zipfile}"
# For LG L5 NoNFC | E612 E617
- export ndevicechoice="1"
- export nbasebuildsh="${ndevice}${ndevicechoice}${nbuild}q"
- source build.sh <<< "${nbasebuildsh}"
- export zipfile1="${zipfile}"
# For LG L7 NFC | P700
- export ndevicechoice="2"
- export nbasebuildsh="${ndevice}${ndevicechoice}${nbuild}q"
- source build.sh <<< "${nbasebuildsh}"
- export zipfile2="${zipfile}"
# For LG L7 NoNFC | P705
- export ndevicechoice="3"
- export nbasebuildsh="${ndevice}${ndevicechoice}${nbuild}q"
- source build.sh <<< "${nbasebuildsh}"
- export zipfile3="${zipfile}"
# For LG L1 II Single/Dual | E410 E411 E415 E420
- export ndevicechoice="4"
- export nbasebuildsh="${ndevice}${ndevicechoice}${nbuild}q"
- source build.sh <<< "${nbasebuildsh}"
- export zipfile4="${zipfile}"
# For LG L3 II Single/Dual | E425 E430 E431 E435"
- export ndevicechoice="5"
- export nbasebuildsh="${ndevice}${ndevicechoice}${nbuild}q"
- source build.sh <<< "${nbasebuildsh}"
- export zipfile5="${zipfile}"
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "tawcLRz5Bm2bgRexze2Zol3pYZqZKe7cwhhDs46TdHMrcrEuMX6bijYTiCYKy/1rLAHr8NGIQOBBF4LXIMouBcQYpzgzlRpFRl6z6NfJOEtXJ3fvyr0JQOOX7QkG7acDnURBHXroI7b+wK4e6f/An9S/1vgSrBKvrYJlQk8OYEt78aOp9GioblvgzfUJx/ZCxvDYSe5dpXuKFBoZyinPuK83ICyWrRViDqVI3JUMo3TPBrTQ/27olNGuoEjZxjU3fATBDc2Im/kZaxoh59OqT4jjKW6i2dDW/GUm5Nl8SxyxRCBCbzGDgCmtXZ4yuqvO5TCsAoPPD4ksZbeywbeHVVViAlsS8majZLedMWwlERL+pW6v9NneaUH+D44881Cq19AepnLq/Oew4F3u6XXqlm69Is3YyJ2WXKqONwa4rbxUyF2hHf2b4bzz7guMtf/MKf/7T4pMKBH6gpRQlD6A9NNS8zhaI5vPzl0B2cPwq9kYPt3DUfWDTxUHi7jztnzja5jk8jXT6DDbNKOqtM7e5In3Hhe0qzbeBYLKyyjwgEoSlsdO6mut6DE4iyRWtbc3MUL+q4O0YDNrvUebuuwxX+PkJwTob0EBlDDLmNpuamhnIFFmjvFWkES86MyId+HGrGrmF2OU6HgAoIITd2FhfYj9Z/C0V00G7cQ2jhCX9eg="
  file:
    - "zip-creator/${zipfile0}"
    - "zip-creator/${zipfile1}"
    - "zip-creator/${zipfile2}"
    - "zip-creator/${zipfile3}"
    - "zip-creator/${zipfile4}"
    - "zip-creator/${zipfile5}"
  on:
    tags: true
